version: "3.7"

x-default-volumes: &default-volumes
  volumes:
    #- ./:/app
    #- node-module:/app/node_module
    - ../naturedb-volumes/bucket:/bucket

services:
  flask:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    #target: flask-dev
    image: naturedb-flask-dev-image
    container_name: naturedb-flask-dev-container
    environment:
      - FLASK_APP=app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=naturedb
    ports:
      - 5000:5000
    volumes:
      - .:/code
      - ../naturedb-volumes/bucket:/bucket
    #command: /srv/start
  postgres:
    image: postgres:14-alpine
    container_name: naturedb-postgres-dev-container
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../naturedb-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../naturedb-volumes/bucket:/bucket
    # command: ["postgres", "-c", "log_statement=all"]
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080