"""article_is_markdown

Revision ID: 04606936e5a1
Revises: 563c639210f3
Create Date: 2022-10-05 08:39:46.616187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04606936e5a1'
down_revision = '563c639210f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_markdown', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'is_markdown')
    # ### end Alembic commands ###
