"""collection.last_taxon

Revision ID: 121e9dcde96b
Revises: 57005904db1f
Create Date: 2022-02-04 20:15:18.448101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121e9dcde96b'
down_revision = '57005904db1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('last_taxon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collection', 'taxon', ['last_taxon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'last_taxon_id')
    # ### end Alembic commands ###
