"""last_taxon_proxy

Revision ID: 1ad2f86e9b14
Revises: 40f612ed9325
Create Date: 2022-09-05 16:16:14.867560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ad2f86e9b14'
down_revision = '40f612ed9325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('proxy_taxon_text', sa.Text(), nullable=True))
    op.add_column('collection', sa.Column('proxy_taxon_id', sa.Integer(), nullable=True))
    op.drop_constraint('collection_last_taxon_id_fkey', 'collection', type_='foreignkey')
    op.create_foreign_key(None, 'collection', 'taxon', ['proxy_taxon_id'], ['id'])
    op.drop_column('collection', 'last_taxon_id')
    op.drop_column('collection', 'proxy_units')
    op.drop_column('collection', 'last_taxon_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('last_taxon_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('collection', sa.Column('proxy_units', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('collection', sa.Column('last_taxon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.create_foreign_key('collection_last_taxon_id_fkey', 'collection', 'taxon', ['last_taxon_id'], ['id'])
    op.drop_column('collection', 'proxy_taxon_id')
    op.drop_column('collection', 'proxy_taxon_text')
    # ### end Alembic commands ###
