"""mof add value_en

Revision ID: 340dbe7a3adf
Revises: 73147e62e571
Create Date: 2022-02-21 08:21:27.495994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340dbe7a3adf'
down_revision = '73147e62e571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_or_fact', sa.Column('value_en', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement_or_fact', 'value_en')
    # ### end Alembic commands ###
