"""param

Revision ID: 3829bcdf4a4d
Revises: f2c40b530b73
Create Date: 2022-01-10 03:01:39.597615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3829bcdf4a4d'
down_revision = 'f2c40b530b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('transaction_type', sa.String(length=500), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('organization_text', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_or_fact_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('measurement_or_fact', sa.Column('paremeter_id', sa.Integer(), nullable=True))
    op.add_column('measurement_or_fact', sa.Column('value', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'measurement_or_fact', 'measurement_or_fact_parameter', ['paremeter_id'], ['id'], ondelete='SET NULL')
    op.drop_column('measurement_or_fact', 'text')
    op.drop_column('measurement_or_fact', 'parameter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_or_fact', sa.Column('parameter', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('measurement_or_fact', sa.Column('text', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'measurement_or_fact', type_='foreignkey')
    op.drop_column('measurement_or_fact', 'value')
    op.drop_column('measurement_or_fact', 'paremeter_id')
    op.drop_table('measurement_or_fact_parameter')
    op.drop_table('transaction')
    # ### end Alembic commands ###
