"""identification add sequence

Revision ID: 43e7ffe83e2a
Revises: 340dbe7a3adf
Create Date: 2022-02-21 08:36:26.138913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e7ffe83e2a'
down_revision = '340dbe7a3adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identification', sa.Column('sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identification', 'sequence')
    # ### end Alembic commands ###
