"""add-proxy-units

Revision ID: 457fefb37290
Revises: 4a9637078fa1
Create Date: 2022-06-22 19:32:38.544269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '457fefb37290'
down_revision = '4a9637078fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('proxy_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'proxy_units')
    # ### end Alembic commands ###
