"""proxy_accession_number

Revision ID: 4a9637078fa1
Revises: 9c2daa1e7249
Create Date: 2022-06-22 18:33:01.126018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9637078fa1'
down_revision = '9c2daa1e7249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('proxy_unit_accession_numbers', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'proxy_unit_accession_numbers')
    # ### end Alembic commands ###
