"""article_pub_by

Revision ID: 563c639210f3
Revises: 27ddcefbc1e2
Create Date: 2022-10-05 08:33:56.954447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '563c639210f3'
down_revision = '27ddcefbc1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('published_by', sa.String(length=500), nullable=True))
    op.add_column('article', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'data')
    op.drop_column('article', 'published_by')
    # ### end Alembic commands ###
