"""collaction.last_taxon

Revision ID: 57005904db1f
Revises: de5bc11a72e3
Create Date: 2022-01-25 17:02:59.982681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57005904db1f'
down_revision = 'de5bc11a72e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('last_taxon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'last_taxon')
    # ### end Alembic commands ###
