"""unit.type

Revision ID: 6e03e535e553
Revises: 69e2521aa765
Create Date: 2022-11-29 19:33:14.857717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e03e535e553'
down_revision = '69e2521aa765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('type_status', sa.String(length=50), nullable=True))
    op.add_column('unit', sa.Column('typified_name', sa.String(length=500), nullable=True))
    op.add_column('unit', sa.Column('type_reference', sa.String(length=500), nullable=True))
    op.add_column('unit', sa.Column('type_identification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unit', 'identification', ['type_identification_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'type_identification_id')
    op.drop_column('unit', 'type_reference')
    op.drop_column('unit', 'typified_name')
    op.drop_column('unit', 'type_status')
    # ### end Alembic commands ###
