"""named_area_parent

Revision ID: 73147e62e571
Revises: f23293e340f3
Create Date: 2022-02-18 09:28:40.970059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73147e62e571'
down_revision = 'f23293e340f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('named_area', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'named_area', 'named_area', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'named_area', type_='foreignkey')
    op.drop_column('named_area', 'parent_id')
    # ### end Alembic commands ###
