"""related_link3

Revision ID: 7d63d6edea63
Revises: 961aeef7b746
Create Date: 2022-12-05 00:52:40.509079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d63d6edea63'
down_revision = '961aeef7b746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organization', 'related_link_category', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'category_id')
    # ### end Alembic commands ###
