"""related_link

Revision ID: 96dd49f18414
Revises: a746a8b419c4
Create Date: 2022-12-05 00:11:20.861629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96dd49f18414'
down_revision = 'a746a8b419c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_link_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('related_link_category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_link_category_id'], ['related_link_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_link')
    op.drop_table('related_link_category')
    # ### end Alembic commands ###
