"""option_group

Revision ID: 9a4457f54d94
Revises: b06746c1cf55
Create Date: 2022-05-01 08:35:27.128589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4457f54d94'
down_revision = 'b06746c1cf55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_or_fact_parameter_option_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('measurement_or_fact_parameter_option', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'measurement_or_fact_parameter_option', 'measurement_or_fact_parameter_option_group', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measurement_or_fact_parameter_option', type_='foreignkey')
    op.drop_column('measurement_or_fact_parameter_option', 'group_id')
    op.drop_table('measurement_or_fact_parameter_option_group')
    # ### end Alembic commands ###
