"""collection.foo_en

Revision ID: a12f7cd17742
Revises: 7834bfdab714
Create Date: 2022-01-15 21:20:07.474049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12f7cd17742'
down_revision = '7834bfdab714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('companion_text_en', sa.String(length=500), nullable=True))
    op.add_column('collection', sa.Column('locality_text_en', sa.String(length=1000), nullable=True))
    op.add_column('collection', sa.Column('note_en', sa.Text(), nullable=True))
    op.drop_column('collection', 'locality_text2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('locality_text2', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('collection', 'note_en')
    op.drop_column('collection', 'locality_text_en')
    op.drop_column('collection', 'companion_text_en')
    # ### end Alembic commands ###
