"""unit.type2

Revision ID: a746a8b419c4
Revises: 6e03e535e553
Create Date: 2022-11-29 20:36:25.471934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a746a8b419c4'
down_revision = '6e03e535e553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identification', 'type_status')
    op.drop_column('identification', 'type_text')
    op.add_column('unit', sa.Column('type_reference_link', sa.String(length=500), nullable=True))
    op.add_column('unit', sa.Column('type_note', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'type_note')
    op.drop_column('unit', 'type_reference_link')
    op.add_column('identification', sa.Column('type_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('identification', sa.Column('type_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
