"""mof option

Revision ID: b06746c1cf55
Revises: d7f65be33cc9
Create Date: 2022-05-01 07:47:11.678221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06746c1cf55'
down_revision = 'd7f65be33cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_or_fact_parameter_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('value_en', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['measurement_or_fact_parameter.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('collection_named_area', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collection_named_area', 'named_area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_named_area', 'named_area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collection_named_area', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('measurement_or_fact_parameter_option')
    # ### end Alembic commands ###
