"""mof-value

Revision ID: b2c3f3ba4a3c
Revises: 457fefb37290
Create Date: 2022-09-05 05:19:30.469327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3f3ba4a3c'
down_revision = '457fefb37290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement_or_fact', 'value_en')
    op.add_column('measurement_or_fact_parameter_option', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement_or_fact_parameter_option', 'description')
    op.add_column('measurement_or_fact', sa.Column('value_en', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
