"""param2

Revision ID: c2a9cbe335ee
Revises: 3829bcdf4a4d
Create Date: 2022-01-10 03:27:15.403524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a9cbe335ee'
down_revision = '3829bcdf4a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
