"""transaction add unit_id

Revision ID: c38fdb886075
Revises: 40b3349a94e2
Create Date: 2022-01-15 22:21:17.316827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38fdb886075'
down_revision = '40b3349a94e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'unit', ['unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'unit_id')
    # ### end Alembic commands ###
