"""article_m

Revision ID: ce68b8dc806f
Revises: 04606936e5a1
Create Date: 2022-10-05 08:56:28.652140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce68b8dc806f'
down_revision = '04606936e5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'published_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('published_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
