"""add_index

Revision ID: de5bc11a72e3
Revises: c2ecfa8d5a53
Create Date: 2022-01-25 13:07:54.891761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5bc11a72e3'
down_revision = 'c2ecfa8d5a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collection_field_number'), 'collection', ['field_number'], unique=False)
    op.create_index(op.f('ix_identification_taxon_id'), 'identification', ['taxon_id'], unique=False)
    op.create_index(op.f('ix_unit_accession_number'), 'unit', ['accession_number'], unique=False)
    op.create_index(op.f('ix_unit_dataset_id'), 'unit', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_dataset_id'), table_name='unit')
    op.drop_index(op.f('ix_unit_accession_number'), table_name='unit')
    op.drop_index(op.f('ix_identification_taxon_id'), table_name='identification')
    op.drop_index(op.f('ix_collection_field_number'), table_name='collection')
    # ### end Alembic commands ###
