"""collection.last_taxon_text

Revision ID: f23293e340f3
Revises: 121e9dcde96b
Create Date: 2022-02-04 20:57:03.423411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23293e340f3'
down_revision = '121e9dcde96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('last_taxon_text', sa.Text(), nullable=True))
    op.drop_column('collection', 'last_taxon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('last_taxon', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('collection', 'last_taxon_text')
    # ### end Alembic commands ###
