"""test-assiciatable

Revision ID: f39056da6198
Revises: 43e7ffe83e2a
Create Date: 2022-03-28 07:51:31.167738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39056da6198'
down_revision = '43e7ffe83e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('named_area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['named_area_id'], ['named_area.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
