#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

#npm run build-dev

#python manage.py migrate --delete-ghost-migrations
#python manage.py migrate
#python manage.py qcluster & python manage.py runserver 0.0.0.0:8000
#gunicorn -b 127.0.0.1:5000 app:app
/root/.local/bin/gunicorn run:app --bind=0.0.0.0:8001
