#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

#npm run build-dev

#python manage.py migrate --delete-ghost-migrations
#python manage.py migrate
#python manage.py qcluster & python manage.py runserver 0.0.0.0:8000
/root/.local/bin/flask run --host 0.0.0.0
