"""person.engilsh_full_name

Revision ID: 586be7ad97a1
Revises: c47b089e9db7
Create Date: 2021-12-27 15:08:41.708638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586be7ad97a1'
down_revision = 'c47b089e9db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('engilsh_full_name', sa.String(length=500), nullable=True))
    op.add_column('person', sa.Column('preferred_name', sa.String(length=500), nullable=True))
    op.drop_column('person', 'preferredName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('preferredName', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('person', 'preferred_name')
    op.drop_column('person', 'engilsh_full_name')
    # ### end Alembic commands ###
