"""person.english_full_name typo

Revision ID: 9a5c0c705a77
Revises: 586be7ad97a1
Create Date: 2021-12-27 17:36:02.829400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5c0c705a77'
down_revision = '586be7ad97a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('english_full_name', sa.String(length=500), nullable=True))
    op.drop_column('person', 'engilsh_full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('engilsh_full_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('person', 'english_full_name')
    # ### end Alembic commands ###
