"""remove annotation

Revision ID: aa1922050156
Revises: 4a056dcb1cd7
Create Date: 2021-12-24 20:03:10.127567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa1922050156'
down_revision = '4a056dcb1cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='annotation_unit_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'unit_id', name='annotation_pkey')
    )
    # ### end Alembic commands ###
